// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ens_mean_and_sd
Rcpp::List ens_mean_and_sd(arma::cube ens);
RcppExport SEXP _mepsr_ens_mean_and_sd(SEXP ensSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type ens(ensSEXP);
    rcpp_result_gen = Rcpp::wrap(ens_mean_and_sd(ens));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mepsr_ens_mean_and_sd", (DL_FUNC) &_mepsr_ens_mean_and_sd, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mepsr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
